apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: webservice
  name: webservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webservice
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - pgcheck
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: bernhard97/webservice:0.1.2
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: webservice
        command: ["./run.rb"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PORT
          value: "8080"

        ports:
          - name: web
            containerPort: 8080

        livenessProbe:
          httpGet:
            port: web
            path: healthz/alive
          initialDelaySeconds: 30
          periodSeconds: 15

        readinessProbe:
          httpGet:
            port: web
            path: healthz/ready
          periodSeconds: 5
          initialDelaySeconds: 25

        resources:
          requests:
            memory: 64Mi
            cpu: 500m
          limits:
            memory: 64Mi
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: webservice
  name: webservice
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webservice
  sessionAffinity: None
  type: ClusterIP
